# -*- coding: utf-8 -*-
"""Canonical built-in role definitions.

One source of truth:
ROLE -> KPI GROUP -> METRIC -> DEFAULT WEIGHT (%)

A metric may have 0% score weight while remaining on the descriptive radar.
This is deliberate for contextual/workload dimensions such as GK shots faced/xGA.
"""
from __future__ import annotations
from typing import Dict, List, Tuple

PROFILE_CONFIG = {'Classic Goalkeeper': {'Shot Stopping': {'Save rate, %': 20,
                                          'Prevented goals per 90': 20,
                                          'Conceded goals per 90': 10,
                                          'Shots against per 90': 0,
                                          'xG against per 90': 0},
                        'Area Control': {'Exits per 90': 10, 'Aerial duels per 90.1': 4, 'Aerial duels won, %': 6},
                        'Distribution': {'Passes per 90': 3,
                                         'Accurate passes, %': 5,
                                         'Long passes per 90': 4,
                                         'Accurate long passes, %': 8},
                        'Build-Up': {'Back passes received as GK per 90': 3,
                                     'Forward passes per 90': 3,
                                     'Accurate forward passes, %': 4}},
 'Sweeper Keeper': {'Sweeping': {'Exits per 90': 12,
                                 'Aerial duels per 90.1': 5,
                                 'Aerial duels won, %': 7,
                                 'Back passes received as GK per 90': 6},
                    'Build-Up': {'Passes per 90': 6,
                                 'Accurate passes, %': 8,
                                 'Forward passes per 90': 7,
                                 'Accurate forward passes, %': 9},
                    'Distribution': {'Long passes per 90': 5,
                                     'Accurate long passes, %': 8,
                                     'Progressive passes per 90': 7},
                    'Shot Stopping': {'Save rate, %': 8,
                                      'Prevented goals per 90': 9,
                                      'Conceded goals per 90': 3,
                                      'Shots against per 90': 0}},
 'Build-Up Keeper': {'Build-Up': {'Back passes received as GK per 90': 6,
                                  'Passes per 90': 7,
                                  'Accurate passes, %': 9,
                                  'Forward passes per 90': 6,
                                  'Accurate forward passes, %': 7},
                     'Progression': {'Progressive passes per 90': 9,
                                     'Passes to final third per 90': 7,
                                     'Accurate progressive passes, %': 9},
                     'Distribution': {'Long passes per 90': 6, 'Accurate long passes, %': 9},
                     'Shot Stopping': {'xG against per 90': 0,
                                       'Save rate, %': 8,
                                       'Prevented goals per 90': 9,
                                       'Conceded goals per 90': 3},
                     'Sweeping': {'Exits per 90': 5}},
 'Ball-Playing CB': {'Build-Up': {'Passes per 90': 4,
                                  'Accurate passes, %': 7,
                                  'Received passes per 90': 3,
                                  'Forward passes per 90': 6},
                     'Progression': {'Progressive passes per 90': 12,
                                     'Accurate progressive passes, %': 10,
                                     'Passes to final third per 90': 8,
                                     'Progressive runs per 90': 5},
                     'Range': {'Long passes per 90': 4, 'Accurate long passes, %': 6},
                     'Defending': {'PAdj Interceptions': 8,
                                   'Defensive duels per 90': 5,
                                   'Defensive duels won, %': 9,
                                   'Aerial duels won, %': 7,
                                   'Successful defensive actions per 90': 6}},
 'Combative CB / Stopper': {'Ground Defending': {'Successful defensive actions per 90': 10,
                                                 'Defensive duels per 90': 9,
                                                 'Defensive duels won, %': 12,
                                                 'PAdj Sliding tackles': 8,
                                                 'PAdj Interceptions': 8},
                            'Possession Security': {'Accurate forward passes, %': 3,
                                                    'Passes per 90': 3,
                                                    'Accurate passes, %': 5,
                                                    'Accurate long passes, %': 4},
                            'Aerial': {'Aerial duels per 90': 7, 'Aerial duels won, %': 11},
                            'Box Defence': {'Shots blocked per 90': 7, 'Sliding tackles per 90': 5},
                            'Aggression / Discipline': {'Fouls per 90': 5, 'Yellow cards per 90': 3}},
 'Libero / Middle Pin CB': {'Build-Up': {'Received passes per 90': 5,
                                         'Passes per 90': 5,
                                         'Accurate passes, %': 8,
                                         'Forward passes per 90': 7},
                            'Progression': {'Progressive passes per 90': 10,
                                            'Accurate progressive passes, %': 10,
                                            'Passes to final third per 90': 7},
                            'Defensive Control': {'PAdj Sliding tackles': 5,
                                                  'PAdj Interceptions': 7,
                                                  'Defensive duels won, %': 7,
                                                  'Aerial duels won, %': 5,
                                                  'Successful defensive actions per 90': 6,
                                                  'Shots blocked per 90': 5},
                            'Distribution': {'Long passes per 90': 5, 'Accurate long passes, %': 8}},
 'Wide CB (in 3)': {'Defending': {'Defensive duels per 90': 7,
                                  'Defensive duels won, %': 9,
                                  'PAdj Interceptions': 8,
                                  'Successful defensive actions per 90': 6},
                    'Carrying': {'Progressive runs per 90': 8,
                                 'Dribbles per 90': 5,
                                 'Successful dribbles, %': 7,
                                 'Accelerations per 90': 5},
                    'Progression': {'Progressive passes per 90': 9,
                                    'Accurate progressive passes, %': 8,
                                    'Passes to final third per 90': 7,
                                    'Forward passes per 90': 6},
                    'Distribution / Security': {'Accurate passes, %': 6,
                                                'Long passes per 90': 4,
                                                'Accurate long passes, %': 5}},
 'Defensive Midfielder #6': {'Ball Winning': {'PAdj Interceptions': 10,
                                              'PAdj Sliding tackles': 7,
                                              'Defensive duels per 90': 7,
                                              'Defensive duels won, %': 10,
                                              'Successful defensive actions per 90': 6},
                             'Availability': {'Received passes per 90': 7,
                                              'Passes per 90': 5,
                                              'Accurate passes, %': 8},
                             'Progression': {'Forward passes per 90': 5,
                                             'Accurate forward passes, %': 5,
                                             'Progressive passes per 90': 8,
                                             'Accurate progressive passes, %': 7,
                                             'Passes to final third per 90': 5},
                             'Mobility / Security': {'Progressive runs per 90': 4, 'Aerial duels won, %': 6}},
 'Deep-Lying Playmaker': {'Involvement': {'Received passes per 90': 7, 'Passes per 90': 7, 'Accurate passes, %': 8},
                          'Progression': {'Forward passes per 90': 7,
                                          'Accurate forward passes, %': 6,
                                          'Progressive passes per 90': 11,
                                          'Accurate progressive passes, %': 10,
                                          'Passes to final third per 90': 9},
                          'Range': {'Long passes per 90': 6, 'Accurate long passes, %': 8, 'Smart passes per 90': 6},
                          'Creation': {'Key passes per 90': 4, 'xA per 90': 4},
                          'Defensive Contribution': {'PAdj Interceptions': 4, 'Defensive duels won, %': 3}},
 'Box-to-Box Midfielder': {'Defending': {'Successful defensive actions per 90': 7,
                                         'Defensive duels per 90': 5,
                                         'Defensive duels won, %': 7,
                                         'PAdj Interceptions': 7},
                           'Progression': {'Progressive runs per 90': 10,
                                           'Progressive passes per 90': 8,
                                           'Accelerations per 90': 7},
                           'Creation': {'xA per 90': 6, 'Shot assists per 90': 5, 'Key passes per 90': 5},
                           'Final Third': {'Touches in box per 90': 7,
                                           'Shots per 90': 5,
                                           'xG per 90': 7,
                                           'Non-penalty goals per 90': 7},
                           'Involvement': {'Received passes per 90': 7}},
 'Playmaker #10': {'Ball Progression': {'Progressive passes per 90': 9,
                                        'Accurate progressive passes, %': 7,
                                        'Progressive runs per 90': 6},
                   'Chance Creation': {'xA per 90': 11,
                                       'Shot assists per 90': 10,
                                       'Key passes per 90': 10,
                                       'Smart passes per 90': 8,
                                       'Deep completions per 90': 6},
                   'Final-Third Distribution': {'Passes to final third per 90': 6,
                                                'Passes to penalty area per 90': 7,
                                                'Through passes per 90': 6},
                   'Attacking Threat': {'Touches in box per 90': 4,
                                        'Shots per 90': 3,
                                        'xG per 90': 3,
                                        'Dribbles per 90': 4}},
 'Full-Back': {'Defending': {'Successful defensive actions per 90': 7,
                             'Defensive duels per 90': 6,
                             'Defensive duels won, %': 9,
                             'PAdj Interceptions': 8,
                             'Aerial duels won, %': 5},
               'Progression': {'Progressive runs per 90': 9,
                               'Progressive passes per 90': 8,
                               'Forward passes per 90': 6,
                               'Accelerations per 90': 7},
               'Delivery': {'Crosses per 90': 6, 'Accurate crosses, %': 8, 'Crosses to goalie box per 90': 6},
               'Creation': {'Passes to penalty area per 90': 5, 'Shot assists per 90': 5, 'xA per 90': 5}},
 'Wing-Back': {'Running / Progression': {'Progressive runs per 90': 11,
                                         'Accelerations per 90': 8,
                                         'Dribbles per 90': 8,
                                         'Successful dribbles, %': 8},
               'Delivery': {'Crosses per 90': 8,
                            'Accurate crosses, %': 8,
                            'Crosses to goalie box per 90': 6,
                            'Passes to penalty area per 90': 7},
               'Creation / Threat': {'Shot assists per 90': 7,
                                     'xA per 90': 8,
                                     'Touches in box per 90': 6,
                                     'Successful attacking actions per 90': 5},
               'Defending': {'Defensive duels per 90': 3, 'Defensive duels won, %': 4, 'PAdj Interceptions': 3}},
 'Inverted Full-Back': {'Build-Up': {'Received passes per 90': 8,
                                     'Passes per 90': 6,
                                     'Accurate passes, %': 8,
                                     'Forward passes per 90': 7},
                        'Progression': {'Progressive passes per 90': 10,
                                        'Accurate progressive passes, %': 9,
                                        'Passes to final third per 90': 7,
                                        'Progressive runs per 90': 6},
                        'Central Distribution': {'Smart passes per 90': 5, 'Accurate forward passes, %': 6},
                        'Defensive Control': {'PAdj Interceptions': 7,
                                              'Defensive duels per 90': 4,
                                              'Defensive duels won, %': 6,
                                              'Successful defensive actions per 90': 6,
                                              'PAdj Sliding tackles': 5}},
 'Classic Winger': {'1v1': {'Dribbles per 90': 10,
                            'Successful dribbles, %': 10,
                            'Offensive duels per 90': 6,
                            'Offensive duels won, %': 7},
                    'Running': {'Progressive runs per 90': 10, 'Accelerations per 90': 7},
                    'Delivery': {'Crosses per 90': 8,
                                 'Accurate crosses, %': 9,
                                 'Crosses to goalie box per 90': 5,
                                 'Passes to penalty area per 90': 5},
                    'Creation': {'Shot assists per 90': 6, 'xA per 90': 7, 'Key passes per 90': 4},
                    'Threat': {'Touches in box per 90': 3, 'Successful attacking actions per 90': 3}},
 'Inverted Winger': {'Scoring': {'Non-penalty goals per 90': 11,
                                 'xG per 90': 11,
                                 'Shots per 90': 8,
                                 'Shots on target, %': 6},
                     '1v1 / Carrying': {'Offensive duels won, %': 5,
                                        'Dribbles per 90': 9,
                                        'Successful dribbles, %': 8,
                                        'Progressive runs per 90': 9,
                                        'Accelerations per 90': 6},
                     'Box Threat': {'Touches in box per 90': 8},
                     'Creation': {'xA per 90': 6,
                                  'Shot assists per 90': 5,
                                  'Key passes per 90': 3,
                                  'Passes to penalty area per 90': 3,
                                  'Deep completions per 90': 2}},
 'Target Man #9': {'Aerial': {'Aerial duels per 90': 11, 'Aerial duels won, %': 13, 'Head goals per 90': 6},
                   'Reference / Link Play': {'Received long passes per 90': 8,
                                             'Received passes per 90': 5,
                                             'Offensive duels per 90': 8,
                                             'Accurate passes, %': 5,
                                             'Fouls suffered per 90': 8},
                   'Box Threat': {'Touches in box per 90': 8,
                                  'xG per 90': 8,
                                  'Shots per 90': 5,
                                  'Non-penalty goals per 90': 7,
                                  'Shots on target, %': 3},
                   'Creation': {'Shot assists per 90': 2, 'xA per 90': 3}},
 'Poacher': {'Scoring': {'Non-penalty goals per 90': 15,
                         'xG per 90': 15,
                         'Shots per 90': 9,
                         'Shots on target, %': 8,
                         'Goal conversion, %': 5},
             'Box Presence': {'Touches in box per 90': 12, 'Received passes per 90': 5, 'Head goals per 90': 4},
             'Movement': {'Progressive runs per 90': 6, 'Accelerations per 90': 4, 'Received long passes per 90': 3},
             'Secondary Creation': {'xA per 90': 3, 'Shot assists per 90': 3},
             'Attack': {'Successful attacking actions per 90': 5, 'Offensive duels won, %': 3}},
 'Pressing Forward': {'Defensive Work': {'Successful defensive actions per 90': 9,
                                         'Defensive duels per 90': 7,
                                         'Defensive duels won, %': 7,
                                         'Fouls per 90': 3,
                                         'PAdj Interceptions': 6},
                      'Mobility': {'Accelerations per 90': 9,
                                   'Progressive runs per 90': 7,
                                   'Offensive duels per 90': 6},
                      'Box Threat': {'Touches in box per 90': 8,
                                     'Shots per 90': 6,
                                     'xG per 90': 8,
                                     'Non-penalty goals per 90': 8},
                      'Link / Creation': {'Received passes per 90': 5, 'Shot assists per 90': 5, 'xA per 90': 6}},
 'Creative Forward / False 9': {'Link Play': {'Received passes per 90': 8,
                                              'Passes per 90': 6,
                                              'Accurate passes, %': 6,
                                              'Forward passes per 90': 4},
                                'Creation': {'xA per 90': 10,
                                             'Shot assists per 90': 9,
                                             'Key passes per 90': 9,
                                             'Smart passes per 90': 8,
                                             'Deep completions per 90': 6},
                                'Progression': {'Progressive passes per 90': 7, 'Progressive runs per 90': 5},
                                'Threat': {'Touches in box per 90': 6,
                                           'xG per 90': 6,
                                           'Shots per 90': 4,
                                           'Non-penalty goals per 90': 6}},
 'Wide Forward / Inside 9': {'Scoring': {'Non-penalty goals per 90': 11,
                                         'xG per 90': 11,
                                         'Shots per 90': 7,
                                         'Shots on target, %': 5,
                                         'Goal conversion, %': 3},
                             'Box Threat': {'Touches in box per 90': 10},
                             'Carrying': {'Progressive runs per 90': 9,
                                          'Accelerations per 90': 5,
                                          'Dribbles per 90': 8,
                                          'Successful dribbles, %': 6},
                             'Creation': {'xA per 90': 6,
                                          'Shot assists per 90': 5,
                                          'Key passes per 90': 4,
                                          'Passes to penalty area per 90': 5,
                                          'Deep completions per 90': 5}}}

ROLE_POSITION_HINTS = {'Classic Goalkeeper': ['GK'],
 'Sweeper Keeper': ['GK'],
 'Build-Up Keeper': ['GK'],
 'Ball-Playing CB': ['CB'],
 'Combative CB / Stopper': ['CB'],
 'Libero / Middle Pin CB': ['CB'],
 'Wide CB (in 3)': ['CB'],
 'Defensive Midfielder #6': ['DMF', 'CMF'],
 'Deep-Lying Playmaker': ['DMF', 'CMF'],
 'Box-to-Box Midfielder': ['CMF', 'DMF', 'AMF'],
 'Playmaker #10': ['AMF', 'CMF'],
 'Full-Back': ['LB', 'RB', 'LWB', 'RWB'],
 'Wing-Back': ['LWB', 'RWB', 'LB', 'RB'],
 'Inverted Full-Back': ['LB', 'RB', 'LWB', 'RWB'],
 'Classic Winger': ['LW', 'RW', 'LWF', 'RWF', 'LMF', 'RMF'],
 'Inverted Winger': ['LW', 'RW', 'LWF', 'RWF', 'LMF', 'RMF'],
 'Target Man #9': ['CF', 'ST'],
 'Poacher': ['CF', 'ST'],
 'Pressing Forward': ['CF', 'ST'],
 'Creative Forward / False 9': ['CF', 'ST', 'AMF'],
 'Wide Forward / Inside 9': ['CF', 'ST', 'LW', 'RW', 'LWF', 'RWF']}

PROFILES: Dict[str, List[str]] = {
    role: [metric for group in groups.values() for metric in group]
    for role, groups in PROFILE_CONFIG.items()
}
SINGLE_PLAYER_PROFILES: Dict[str, List[Tuple[str, str]]] = {
    role: [(kpi, metric) for kpi, metrics in groups.items() for metric in metrics]
    for role, groups in PROFILE_CONFIG.items()
}
DEFAULT_WEIGHTS: Dict[str, Dict[str, int]] = {
    role: {metric: int(weight) for metrics in groups.values() for metric, weight in metrics.items()}
    for role, groups in PROFILE_CONFIG.items()
}

def kpi_for_metric(role: str, metric: str) -> str:
    for kpi, metrics in PROFILE_CONFIG.get(role, {}).items():
        if metric in metrics:
            return kpi
    return "Profile"

def validate_profile_config() -> List[str]:
    issues: List[str] = []
    if len(PROFILE_CONFIG) != 21:
        issues.append(f"Expected 21 built-in profiles, found {len(PROFILE_CONFIG)}.")
    for role, groups in PROFILE_CONFIG.items():
        metrics = [m for d in groups.values() for m in d]
        if len(metrics) != 15:
            issues.append(f"{role}: expected 15 metrics, found {len(metrics)}.")
        if len(metrics) != len(set(metrics)):
            issues.append(f"{role}: duplicate metric detected.")
        total = sum(int(w) for d in groups.values() for w in d.values())
        if total != 100:
            issues.append(f"{role}: default weights total {total}%, expected 100%.")
        bad = [m for m in metrics if not ("per 90" in m or "%" in m or m.startswith("PAdj "))]
        if bad:
            issues.append(f"{role}: normalization-policy issue: {', '.join(bad)}")
    return issues
